project:
  type: website
  output-dir: docs

website:
  title: "Neuro-iX.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: 
      light: light_config.scss
      dark: dark_config.scss
      
    #maintfont: arial
    #fontsize: 1rem
    #fontcolor: "#000000" #Color of text
    #linkcolor: "#2e97f4" #color of links
    #monofont: courier new #font of text
    css: styles.css
    toc: true



