project:
  type: website
  output-dir: docs

website:
  title: "Neuro-iX.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      
format:
  html:
    theme: 
      light: themes/light_config.scss
      dark: themes/dark_config.scss
    css: styles.css
    toc: true



