---
title: Prospective Students
pagetitle: "Prospective Students"
jupyter: python3
---

**We are recruiting!**

The Neuro-iX lab at École de Technologie Supérieure (ÉTS) in Montréal sits at the cutting edge of neuroimaging and computational neuroscience, developing the next generation of open-source AI tools for MRI processing and analysis. Our goal is to make sophisticated neuroimaging methods more accessible, reproducible, and impactful for researchers and clinicians worldwide — turning rich, large-scale multimodal datasets into meaningful discoveries about the brain in health and disease. Based in the vibrant, multicultural city of Montréal — a world-class hub for AI research — Neuro-iX is an exciting place to build your career at the intersection of neuroscience, image analysis and artificial intelligence. If this resonates with you, we would love to hear from you.
Please apply through our online application form. The application deadline is May 31. 



::: {.text-center}

[**Apply Now**](https://forms.office.com/r/qK1sSt2QKe){.btn style="background-color:black; color:white; border:none;"}

:::

<!--
[Apply Now](https://forms.office.com/r/qK1sSt2QKe){target="_blank"}
If you’re interested in joining the lab, please [fill out this form](https://docs.google.com/forms/d/e/1FAIpQLSfUGxxQXknK1EXk4omb1Iyi5yVZHz5zsrpesy027biK0POcrg/viewform){target="_blank"}.

For all other enquiries email [Sylvain Bouix](mailto:sylvain.bouix@etsmtl.ca){target="_blank"}.-->